package cmd

// nolint
const (
	DIRENV_CONFIG = "DIRENV_CONFIG"
	DIRENV_BASH   = "DIRENV_BASH"
	DIRENV_DEBUG  = "DIRENV_DEBUG"

	DIRENV_DIR      = "DIRENV_DIR"
	DIRENV_FILE     = "DIRENV_FILE"
	DIRENV_WATCHES  = "DIRENV_WATCHES"
	DIRENV_DIFF     = "DIRENV_DIFF"
	DIRENV_REQUIRED = "DIRENV_REQUIRED"
	DIRENV_STATE    = "DIRENV_STATE"

	DIRENV_DUMP_FILE_PATH = "DIRENV_DUMP_FILE_PATH"

	DIRENV_HOOK_PREFIX = "DIRENV_HOOK_"
	HOOK_SET_PROCESS_MARKER = "SET_PROCESS_MARKER"
	HOOK_UNSET_PROCESS_MARKER = "UNSET_PROCESS_MARKER"
	HOOK_UNLOAD = "UNLOAD"
	HOOK_PRE_LOAD = "PRE_LOAD"
	HOOK_POST_LOAD = "POST_LOAD"
)
